services:
  backend-testing:
    build: 
      context: .
      dockerfile: development.dockerfile
    command: bash -c 'uvicorn app.app:app --reload --host 0.0.0.0 --port 7827'
    volumes:
      - test_data:/backend
      - ./acts:/backend/acts
      - ./logs:/backend/logs
    ports:
      - '127.0.0.1:7827:7827'

volumes:
  test_data:
